# Development compose file.

version: '2'
services:
  web:
    build: . # Can't be below this since we have to add files in public/
    ports:
     - "8082:80"
    volumes:
     - slac-web:/var/www/html
    external_links:
     - slac-mysql:mysql
    environment:
     - ENVIRONMENT=DEV
     - DRUPAL_INSTALL=TRUE
     - SITE_URL=http://docker.slac.stanford.edu:8082
     - HTPASSWD_USER
     - HTPASSWD_PASSWORD
    networks:
     - mysql_default
volumes:
  slac-web:
    external: true 
networks: 
  mysql_default:
    external: true
