module:
  block: 0
  block_content: 0
  breakpoint: 0
  ckeditor: 0
  color: 0
  config: 0
  datetime: 0
  datetime_range: 0
  dblog: 0
  dynamic_page_cache: 0
  editor: 0
  feeds: 0
  field: 0
  field_ui: 0
  file: 0
  filter: 0
  image: 0
  imce: 0
  layout_discovery: 0
  link: 0
  menu_ui: 0
  node: 0
  options: 0
  page_cache: 0
  path: 0
  rdf: 0
  serialization: 0
  system: 0
  text: 0
  token: 0
  toolbar: 0
  update: 0
  user: 0
  views_ui: 0
  webform: 0
  webform_example_composite: 0
  webform_example_element: 0
  webform_examples: 0
  webform_node: 0
  webform_scheduled_email: 0
  webform_score: 0
  webform_templates: 0
  webform_ui: 0
  menu_link_content: 1
  views: 10
  minimal: 1000
theme:
  stable: 0
  material_base: 0
  material_cascade: 0
  classy: 0
  material_admin: 0
profile: minimal
_core:
  default_config_hash: R4IF-ClDHXxblLcG0L7MgsLvfBIMAvi_skumNFQwkDc
